name: Sapphire-Test-Plugin
version: ${version}
main: io.sapphiremc.sapphire.test.SapphireTestPlugin
description: Plugin for testing sapphire features
author: SapphireMC
api-version: ${apiVersion}
load: STARTUP
