name: Sapphire-Test-Plugin
version: ${version}
main: io.sapphiremc.sapphire.test.SapphireTestPlugin
description: Plugin for testing sapphire features
author: SapphireMC
api-version: ${apiVersion}
load: STARTUP

commands:
  testnbt:
    description: "Run all nbt tests and print its results"
    permission: "sapphire.tests.nbt"

permissions:
  sapphire.tests.*:
    description: "Allows you to run all our tests"
    default: op
    children:
      - "sapphire.tests.nbt"

  sapphire.tests.nbt:
    description: "Allows you to run nbt tests"
    default: op