name: Sapphire-Test-Plugin
version: ${version}
main: io.sapphiremc.sapphire.testplugin.SapphireTestPlugin
description: Plugin for testing sapphire features
author: SapphireMC
api-version: ${apiVersion}
load: STARTUP

commands:
  test:
    description: "Run all nbt tests and print its results"
    permission: "sapphiretest.command.test"

permissions:
  sapphiretest.command.test:
    description: "Allows you to run all our tests"
    default: op
