name: Sapphire-Test-Plugin
version: ${version}
main: io.sapphiremc.sapphire.testplugin.SapphireTestPlugin
description: Plugin for testing sapphire features
author: SapphireMC
api-version: ${apiVersion}
load: STARTUP

commands:
  tests:
    description: "Run all nbt tests and print its results"
    permission: "sapphire.command.tests"

permissions:
  sapphire.command.tests:
    description: "Allows you to run all our tests"
    default: op
