name: Publish
on: [ push ]
concurrency: ci-${{ github.ref }}
jobs:
  publish:
    if: ${{ github.repository_owner == 'SapphireMC' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Patch and publish to repo
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew applyPatches --stacktrace
          ./gradlew publish --stacktrace
        env:
          NO_SERVER_PUBLISH: true
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
